### ISSUE TITLE
ui-dropdown: Manuell positionering

### ISSUE THREAD

**Issue by marthings** [digilar/ember-cli-compton#12]
Vi skulle behöva möjlighet att "nudga" positionen på dropdownen från antingen vänster eller höger. Jag hade tidigare ett koncept för detta just för att t.ex få pilen att peka på "rätt" ställe.

{{#ui-dropdown isOpen=isOpen position='auto' nudgeRight='-190px' arrow='center' }}

blir: 

<div class="ui-dropdown" style="right: -190px">

Då kan vi enkelt tweaka positionen per case. Ett exempel nu är ju i babel där pilen i topmenyn inte riktigt pekar på ikonen. Där skulle man vilja typ:

{{#ui-dropdown isOpen=isOpen position='auto' nudgeRight='-5px' arrow='center' }}

**Comment by Sonberg** [comment]
Detta är löst. Genom att sätta position="auto" och left,right,top,bottom kan positionen förändras.

ui-dropdown behöver stöd för:

- Att placerars över och under en komponent.
- Pil i botten (till exempel arrow="bottom right")
- Inte positioneras utanför eller "översvämma" skärmen
