### ISSUE TITLE
context-menu

### ISSUE THREAD

**Issue by marthings** [digilar/ember-cli-compton#13]
Helst köra m.item som ett block så att vi kan populera varje item med valfri markup / ikon / annan komponent t.ex. Vill helst se att vi kör block rakt igenom också för att slippa att vi gör på olika sätt i olika contextmenus i våra tre projekt framövrer

{{#m.item}}ikon + text + someaction maybe{{/m.item}}

Istället för

{{m.item här kan vi inte populera med markup}}

**Comment by tornroth** [comment]
Ja, det är ändrat. Nu gäller:

`{{#m.item onClick=(action "someAction")}}ikon + text{{/m.item}}`
