### ISSUE TITLE
component-css

### ISSUE THREAD

**Issue by Sonberg** [digilar/ember-cli-compton#2]
<img width="1458" alt="skarmavbild 2017-06-12 kl 20 38 42" src="https://user-images.githubusercontent.com/11244968/27049399-7f3e4448-4faf-11e7-8d77-b096f5646bfb.png">

Slack-diskussion med skaparen

**Comment by mwahss** [comment]
Jehova?

**Comment by marthings** [comment]
Så det funkar inte :/?

**Comment by marthings** [comment]
https://github.com/salsify/ember-css-modules/blob/master/README.md Oh här har vi annars något intressant! Detta är riktigt grymt med composes t.ex. Detta används ju i react ofta

**Comment by marthings** [comment]
Känns som att css modules t.o.m verkar vara en bättre lösning än css-component vi kör nu

**Comment by marthings** [comment]
Kanske inte löser problemet med addon / app dock. Verkar i alla fall som att vi skulle kunna rakt av byta till css modules för att testa bara iaf. (Många svar nu :p kan inte redigera inlägg på mobil verkar det som)
