### ISSUE TITLE
ui-tag: Förmatade värden syns inte

### ISSUE THREAD

**Issue by jmillegard** [digilar/ember-cli-compton#3]
Testar ui-tag och funkar inte när jag skickar in en array såhär: {{ui-tag value=data}} ui-tag är fortfarande tom. Data innehåller en array med strängar.

Däremot så skickas värderna tillbaka som jag skriver. MEN jag måste trycka Enter för att dom ska sparas. Kan ju finnas en risk med att man skriver i något och glömmer trycka enter och så sparas det inte. Kanske inte är ett problem men tar bara upp det.

**Comment by Sonberg** [comment]
Mina förmatade värden visas, kan du kontrollera att problemet återstår. En ny tagg spara på enter och fokus ut, ska vi ändra på detta?
